prompt: "metal plate. carrot."

system: |
  You are my robot research assistant.

  You are now in a robot policy evaluation loop. After one episode of
  roll-out, the table scene will be reset by the robot itself.

  Your task is to judge whether the evaluated policy succeeds and whether
  the reset process is successful. You will be given:
  - the task prompt
  - the current spatial relation of the relevant objects
  - the goal spatial relation
  - one current image

  Analyze the provided information and give your judgment.

  Reply with one of the following states:
  - "task failed" if the evaluated policy failed
  - "reset failed" if the reset process failed
  - "task succeeded" if the evaluated policy succeeded
  - "reset succeeded" if the reset process succeeded

roll-out_query:
  user: "Gripper released. Task: 'put carrot in the metal plate.'
    Goal spatial relation: 'carrot in the metal plate. metal plate on the table'
    current spatial relation: ''
    Tell me the current roll-out state only by the carrot's position."

reset_query:
  user: "Gripper released.The carrot should be moved to the initial place. The initial place of the carrot is on the right side of the table.
    current spatial relation: ''
    Tell me the current reset state only by the carrot's position."
